---
title: "range_expansion"
author: "Amanda Stahlke"
date: "3/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``````{r, engine = 'bash', eval = FALSE, plinkcode}
## convert this contig vcf to plink
module load plink/1.90

plink --bfile contig.populations.snps --set-missing-var-ids "@_#" --make-bed --out contig.populations.snps --allow-extra-chr
``````

```{r}
## range expansion
library(rangeExpansion) ## Version: 0.0.0.9000
library(dplyr)
library(snpStats) #1.32.0
library(geosphere)
library(rworldmap)

library(ggplot2)
```


## make coords file

```{r make_inputs}
snp.file <- "contig.populations.snps.bed"
geneticdat <- load.plink.file(snp.file)
nrow(geneticdat$genotypes) # 154 individuals
id <- data.frame(id = rownames(geneticdat$genotypes))

### make coords_file: id, longitude, latitude, outgroup, region, pop
sample_meta.dat <- read.csv("../info/pop_metadata.csv", header = TRUE, stringsAsFactors = FALSE)
ind_map <- read.csv("intro_carinu_popmap.tsv", sep = "\t", header = F, col.names = c("id", "popID"))
nrow(ind_map)

meta_ind <- merge(sample_meta.dat, ind_map) %>%
  select(c(id, Longitude, Latitude, popID))

meta_ind$id <- gsub('_rep', "", meta_ind$id)
meta_ind$id <- gsub('_2019', "", meta_ind$id)

## from population substructure
carinu_regions <- data.frame(popID=unique(meta_ind$popID), region = c(1, #11CO
                                                                      2, #12AZ
                                                                      1, #18TX
                                                                      1, #1WY
                                                                      1, #28NM
                                                                      1, #2CO
                                                                      2, #31NV
                                                                      2, #32UT
                                                                      2, #33NV
                                                                      2, #34UT
                                                                      1, #4CO
                                                                      1, #5CO 
                                                                      1))

carinu_meta_regions <- merge(meta_ind, carinu_regions)


colnames(carinu_meta_regions)

## col order  = id, longitude, latitude, pop, region
colnames(carinu_meta_regions)[c(1,3,4)] <- c('pop','longitude', 'latitude')

carinu_meta_regions <- carinu_meta_regions[,c('id','longitude', 'latitude', 'pop', 'region')]
carinu_meta_regions

xlen = max(carinu_meta_regions$longitude)-min(carinu_meta_regions$longitude) + 10

ylen = max(carinu_meta_regions$latitude)-min(carinu_meta_regions$latitude) +10

write.csv(carinu_meta_regions, "carinu_meta_regions.csv", 
          quote = F, row.names = F)
```

```{r all_intro_carinu_run, cache=T}
snp.file <- "contig.populations.snps.bed" # should be renamed 
carinu_coords.file <- "carinu_meta_regions.csv"
regions_to_analyze <- list(NULL,
                           "1", 
                           "2",
                           c("1", "2"))
ploidy <- 2 #diploid individuals

raw.data <- load.data(plink.file = snp.file, coords.file = carinu_coords.file, sep = ",", ploidy=ploidy)

pop <- make.pop(raw.data, ploidy)

psi <- get.all.psi(pop)

results <- run.regions(region=regions_to_analyze, psi = psi,  pop=pop, xlen=25, ylen=25)
results_summary <- summary(results)

rbind(orgin_1 = as.data.frame(results_summary$`1`), 
           origin_2 = as.data.frame(results_summary$`2`),
           origin_1_2 = as.data.frame(results_summary$`1+2`))

plot.origin.result.list(results)
```

## psi is directionality index

```{r psi}
my_psi <- as.matrix(psi)
rownames(my_psi) <- pop$coords$pop
colnames(my_psi) <- pop$coords$pop

melted_cormat <- reshape2::melt(my_psi, na.rm = TRUE)
melted_cormat <- melted_cormat[order(melted_cormat$value, decreasing = TRUE),]
melted_cormat$Var1 <- factor(melted_cormat$Var1, levels=unique(melted_cormat$Var1[order(melted_cormat$value)]))
melted_cormat$Var2 <- factor(melted_cormat$Var2, levels=unique(melted_cormat$Var2[order(melted_cormat$value)]))

# library(ggplot2)
ggplot(data = melted_cormat, aes(Var1, Var2, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-.3,.3), space = "Lab", 
                       name="Psi") +
  xlab("Psi_1") +
  ylab("Psi_2") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()
ggsave("range_expansion_psi.jpeg", dpi = 300)

```
## Try again with samples only along virgin river expansion

```{r}
snp.file <- "virgin-river.contig.populations.snps"
geneticdat <- load.plink.file(snp.file)
nrow(geneticdat$genotypes) # 67 individuals
id <- data.frame(id = rownames(geneticdat$genotypes))

ploidy <- 2 #diploid individuals

### make coords_file: id, longitude, latitude, outgroup, region, pop
sample_meta.dat
ind_map <- read.csv("intro_carinu_popmap.tsv", sep = "\t", header = F, col.names = c("id", "popID"))
ind_map$id <- gsub('_rep', "", ind_map$id)
ind_map$id <- gsub('_2019', "", ind_map$id)

ind_map <- merge(id, ind_map)


meta_ind <- merge(sample_meta.dat, ind_map) %>%
  select(c(id, Longitude, Latitude, popID))
meta_ind

unique(meta_ind$popID)
virgin_meta_regions <- merge(meta_ind, carinu_regions)
colnames(virgin_meta_regions)[c(1,3,4)] <- c('pop','longitude', 'latitude')
View(virgin_meta_regions)

virgin_meta_regions <- virgin_meta_regions[,c('id','longitude', 'latitude', 'pop')]
## missing region; add this back in 
# write.csv(virgin_meta_regions, "virgin_meta_regions.csv", quote = F, row.names = F)

```

```{r}
snp.file <- "virgin-river.contig.populations.snps"
coords.file <- "virgin_meta_regions.csv"
region <- list(NULL, "1")


raw.data <- load.data(plink.file = snp.file, coords.file = coords.file, sep = ",", ploidy=ploidy)
pop <- make.pop(raw.data, ploidy)
psi <- get.all.psi(pop)
results <- run.single.region(region=region, pop=pop, psi=psi, xlen=20,ylen=20)
summary(results)
plot(results, add.map=T)
plot.origin.results(results, add.map=T)

```

```{r}
my_psi <- as.matrix(psi)
rownames(my_psi) <- pop$coords$pop
colnames(my_psi) <- pop$coords$pop
max(my_psi)
# heatmap(my_psi, Rowv = TRUE, symm = TRUE, col = heat.colors(256), margins=c(5,10))
# ?heatmap
# my_psi$pop1 <- rownames(my_psi)
melted_cormat <- reshape2::melt(my_psi, na.rm = TRUE)

melted_cormat <- melted_cormat[order(melted_cormat$value, decreasing = TRUE),]
melted_cormat$Var1 <- factor(melted_cormat$Var1, levels=unique(melted_cormat$Var1[order(melted_cormat$value)]))
melted_cormat$Var2 <- factor(melted_cormat$Var2, levels=unique(melted_cormat$Var2[order(melted_cormat$value)]))

ggplot(data = filter(melted_cormat, value >0), aes(Var1, Var2, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(0,max(my_psi)), space = "Lab", 
                       name="Psi") +
  xlab("Psi_1") +
  ylab("Psi_2") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()
```

